### ISSUE TITLE
Do you ignore setting meta viewport in media-queries step

### ISSUE THREAD

**Issue by GKennyKwok** [mdn/css-examples#21]
No media response after changing resolution

**Comment by x-N0** [comment]
This Issue is far from being understandable, you at least may try explaining the issue, where do you had the issue, the piece of hardware that you used, If this happened in just one page or all the pages, I dont even know about what page you are talking about: The examples? A certain piece of the webpage?
I hope this response helps you to improve your issue, so the contributors can work on it.

**Comment by avivmu** [comment]
@chrisdavidmills looks closable
