### ISSUE TITLE
background-color: rgba(0,0,0,.5);该属性值最后一个参数，无法设置文字透明！

### ISSUE THREAD

**Issue by dingguangbo** [mdn/css-examples#36]
1. 

[https://github.com/mdn/css-examples/blob/master/learn/solutions.md#backgrounds-and-borders](url)该文档中要求，使用rgba颜色为半透明的标题添加了背景颜色， **background-color: rgba(0,0,0,.5);这个属性值中最后一个参数无法让文字透明**（无法让标题透明）。如果让文字在背景中透明，**正确的方法应该使用opacity**: 0.5;这个属性！

2. 

最初学习文档是[https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders](url)玩转背景和边框中，第3个要求：给h2标题一个半透明的黑色背景颜色，并使文本为白色。但是解决方案中用了background-color: rgba(0,0,0,.5);所以这个不对的。

**Comment by yarusome** [comment]
Either the current en-US [version](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Test_your_skills_backgrounds_and_borders#task_1) of the test says:

> 3. Give the `<h2>` a semi-transparent black background color, and make the text white.

or the current zh-CN [version](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders#%E7%8E%A9%E8%BD%AC%E8%83%8C%E6%99%AF%E5%92%8C%E8%BE%B9%E6%A1%86) says:

> 3. 给&lt;h2&gt;一个半透明的黑色背景颜色，并使文本为白色。

Both clearly suggest that it's the **background** instead of the **text** that needs to be semi-transparent, so this issue is out of misunderstanding.

@estelle or @teoli2003, could you close this issue? Thanks in advance!

**Comment by yin1999** [comment]
> Both clearly suggest that it's the **background** instead of the **text** that needs to be semi-transparent, so this issue is out of misunderstanding.

:+1:, I think we could close this :)

**Comment by estelle** [comment]
Yes. This is correct. The background, not the text, should be semi-opaque.
